name: neo
description: Tool that helps you to run code generation commands.
version: 1.0.0-dev-1
homepage: https://github.com/shan-shaji/neo

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  mason_logger: ^0.2.3
  path: ^1.8.3
  pub_updater: ^0.2.1
  pubspec_parse: ^1.2.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

executables:
  neo:
